<?php

/**
 * @file redesign_staging.install
 *
 * Add hook_enable(), etc.
 *
 */

/**
 * Implements hook_enable()
 */
function redesign_staging_enable() {
  $sql = "UPDATE languages SET domain=REPLACE(domain, 'aplv.org', 'aplv.thefays.us')";
  db_query($sql);
  drupal_set_message('Set domain to aplv.thefays.us instead of aplv.org');
  module_disable(array('backup_migrate'));
  drupal_set_message('Disabled backup_migrate');
}
