<?php
/**
 * @file
 * redesign_block.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function redesign_block_default_fe_block_settings() {
  $export = array();

  $export['version'] = '1.0';

  // Theme independent visibility settings.
  $export['visibility'] = array(
    'nodeblock-203' => array(
      'delta' => '203',
      'module' => 'nodeblock',
    ),
    'nodeblock-204' => array(
      'delta' => '204',
      'module' => 'nodeblock',
    ),
    'nodeblock-205' => array(
      'delta' => '205',
      'module' => 'nodeblock',
    ),
    'nodeblock-206' => array(
      'delta' => '206',
      'module' => 'nodeblock',
    ),
    'nodeblock-207' => array(
      'delta' => '207',
      'module' => 'nodeblock',
    ),
    'nodeblock-208' => array(
      'delta' => '208',
      'module' => 'nodeblock',
    ),
    'nodeblock-209' => array(
      'delta' => '209',
      'module' => 'nodeblock',
    ),
    'nodeblock-210' => array(
      'delta' => '210',
      'module' => 'nodeblock',
    ),
    'nodeblock-211' => array(
      'delta' => '211',
      'module' => 'nodeblock',
    ),
    'nodeblock-212' => array(
      'delta' => '212',
      'module' => 'nodeblock',
    ),
    'nodeblock-213' => array(
      'delta' => '213',
      'module' => 'nodeblock',
    ),
    'nodeblock-214' => array(
      'delta' => '214',
      'module' => 'nodeblock',
    ),
    'nodeblock-215' => array(
      'delta' => '215',
      'module' => 'nodeblock',
    ),
    'nodeblock-216' => array(
      'delta' => '216',
      'module' => 'nodeblock',
    ),
    'nodeblock-217' => array(
      'delta' => '217',
      'module' => 'nodeblock',
    ),
    'nodeblock-218' => array(
      'delta' => '218',
      'module' => 'nodeblock',
    ),
    'nodeblock-219' => array(
      'delta' => '219',
      'module' => 'nodeblock',
    ),
    'nodeblock-220' => array(
      'delta' => '220',
      'module' => 'nodeblock',
    ),
    'nodeblock-221' => array(
      'delta' => '221',
      'module' => 'nodeblock',
    ),
    'nodeblock-222' => array(
      'delta' => '222',
      'module' => 'nodeblock',
    ),
    'nodeblock-223' => array(
      'delta' => '223',
      'module' => 'nodeblock',
    ),
  );

  // aplv2012d7
  $theme = array();

  $theme['nodeblock-203'] = array(
    'module' => 'nodeblock',
    'delta' => '203',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-204'] = array(
    'module' => 'nodeblock',
    'delta' => '204',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-205'] = array(
    'module' => 'nodeblock',
    'delta' => '205',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-206'] = array(
    'module' => 'nodeblock',
    'delta' => '206',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-207'] = array(
    'module' => 'nodeblock',
    'delta' => '207',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-208'] = array(
    'module' => 'nodeblock',
    'delta' => '208',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-209'] = array(
    'module' => 'nodeblock',
    'delta' => '209',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-210'] = array(
    'module' => 'nodeblock',
    'delta' => '210',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-211'] = array(
    'module' => 'nodeblock',
    'delta' => '211',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-212'] = array(
    'module' => 'nodeblock',
    'delta' => '212',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-213'] = array(
    'module' => 'nodeblock',
    'delta' => '213',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-214'] = array(
    'module' => 'nodeblock',
    'delta' => '214',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-215'] = array(
    'module' => 'nodeblock',
    'delta' => '215',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-216'] = array(
    'module' => 'nodeblock',
    'delta' => '216',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-217'] = array(
    'module' => 'nodeblock',
    'delta' => '217',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-218'] = array(
    'module' => 'nodeblock',
    'delta' => '218',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-219'] = array(
    'module' => 'nodeblock',
    'delta' => '219',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-220'] = array(
    'module' => 'nodeblock',
    'delta' => '220',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-221'] = array(
    'module' => 'nodeblock',
    'delta' => '221',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-222'] = array(
    'module' => 'nodeblock',
    'delta' => '222',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-223'] = array(
    'module' => 'nodeblock',
    'delta' => '223',
    'theme' => 'aplv2012d7',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $export['theme']['aplv2012d7'] = $theme;

  // aplv_new
  $theme = array();

  $theme['nodeblock-203'] = array(
    'module' => 'nodeblock',
    'delta' => '203',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-204'] = array(
    'module' => 'nodeblock',
    'delta' => '204',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-205'] = array(
    'module' => 'nodeblock',
    'delta' => '205',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-206'] = array(
    'module' => 'nodeblock',
    'delta' => '206',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-207'] = array(
    'module' => 'nodeblock',
    'delta' => '207',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-208'] = array(
    'module' => 'nodeblock',
    'delta' => '208',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-209'] = array(
    'module' => 'nodeblock',
    'delta' => '209',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-210'] = array(
    'module' => 'nodeblock',
    'delta' => '210',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-211'] = array(
    'module' => 'nodeblock',
    'delta' => '211',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-212'] = array(
    'module' => 'nodeblock',
    'delta' => '212',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-213'] = array(
    'module' => 'nodeblock',
    'delta' => '213',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-214'] = array(
    'module' => 'nodeblock',
    'delta' => '214',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-215'] = array(
    'module' => 'nodeblock',
    'delta' => '215',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-216'] = array(
    'module' => 'nodeblock',
    'delta' => '216',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-217'] = array(
    'module' => 'nodeblock',
    'delta' => '217',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-218'] = array(
    'module' => 'nodeblock',
    'delta' => '218',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-219'] = array(
    'module' => 'nodeblock',
    'delta' => '219',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-220'] = array(
    'module' => 'nodeblock',
    'delta' => '220',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-221'] = array(
    'module' => 'nodeblock',
    'delta' => '221',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-222'] = array(
    'module' => 'nodeblock',
    'delta' => '222',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-223'] = array(
    'module' => 'nodeblock',
    'delta' => '223',
    'theme' => 'aplv_new',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $export['theme']['aplv_new'] = $theme;

  // garland
  $theme = array();

  $theme['nodeblock-203'] = array(
    'module' => 'nodeblock',
    'delta' => '203',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-204'] = array(
    'module' => 'nodeblock',
    'delta' => '204',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-205'] = array(
    'module' => 'nodeblock',
    'delta' => '205',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-206'] = array(
    'module' => 'nodeblock',
    'delta' => '206',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-207'] = array(
    'module' => 'nodeblock',
    'delta' => '207',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-208'] = array(
    'module' => 'nodeblock',
    'delta' => '208',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-209'] = array(
    'module' => 'nodeblock',
    'delta' => '209',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-210'] = array(
    'module' => 'nodeblock',
    'delta' => '210',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-211'] = array(
    'module' => 'nodeblock',
    'delta' => '211',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-212'] = array(
    'module' => 'nodeblock',
    'delta' => '212',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-213'] = array(
    'module' => 'nodeblock',
    'delta' => '213',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-214'] = array(
    'module' => 'nodeblock',
    'delta' => '214',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-215'] = array(
    'module' => 'nodeblock',
    'delta' => '215',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-216'] = array(
    'module' => 'nodeblock',
    'delta' => '216',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-217'] = array(
    'module' => 'nodeblock',
    'delta' => '217',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-218'] = array(
    'module' => 'nodeblock',
    'delta' => '218',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-219'] = array(
    'module' => 'nodeblock',
    'delta' => '219',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-220'] = array(
    'module' => 'nodeblock',
    'delta' => '220',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-221'] = array(
    'module' => 'nodeblock',
    'delta' => '221',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-222'] = array(
    'module' => 'nodeblock',
    'delta' => '222',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-223'] = array(
    'module' => 'nodeblock',
    'delta' => '223',
    'theme' => 'garland',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $export['theme']['garland'] = $theme;

  // seven
  $theme = array();

  $theme['nodeblock-203'] = array(
    'module' => 'nodeblock',
    'delta' => '203',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-204'] = array(
    'module' => 'nodeblock',
    'delta' => '204',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-205'] = array(
    'module' => 'nodeblock',
    'delta' => '205',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-206'] = array(
    'module' => 'nodeblock',
    'delta' => '206',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-207'] = array(
    'module' => 'nodeblock',
    'delta' => '207',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-208'] = array(
    'module' => 'nodeblock',
    'delta' => '208',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-209'] = array(
    'module' => 'nodeblock',
    'delta' => '209',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-210'] = array(
    'module' => 'nodeblock',
    'delta' => '210',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-211'] = array(
    'module' => 'nodeblock',
    'delta' => '211',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-212'] = array(
    'module' => 'nodeblock',
    'delta' => '212',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-213'] = array(
    'module' => 'nodeblock',
    'delta' => '213',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-214'] = array(
    'module' => 'nodeblock',
    'delta' => '214',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-215'] = array(
    'module' => 'nodeblock',
    'delta' => '215',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-216'] = array(
    'module' => 'nodeblock',
    'delta' => '216',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-217'] = array(
    'module' => 'nodeblock',
    'delta' => '217',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-218'] = array(
    'module' => 'nodeblock',
    'delta' => '218',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-219'] = array(
    'module' => 'nodeblock',
    'delta' => '219',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-220'] = array(
    'module' => 'nodeblock',
    'delta' => '220',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-221'] = array(
    'module' => 'nodeblock',
    'delta' => '221',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-222'] = array(
    'module' => 'nodeblock',
    'delta' => '222',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $theme['nodeblock-223'] = array(
    'module' => 'nodeblock',
    'delta' => '223',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
    'i18n_mode' => '0',
  );

  $export['theme']['seven'] = $theme;

  $theme_default = variable_get('theme_default', 'garland');
  $themes = list_themes();
  foreach ($export as $theme_key => $settings) {
    if ($theme_key != $theme_default && empty($themes[$theme_key]->status)) {
      unset($export['theme'][$theme_key]);
    }
  }
  return $export;
}
